import type { Env } from "./env";
import { adminStatus, createPromotion, listAdminUsers } from "./admin";
import { authenticate, claimLegacyData } from "./auth";
import { downloadAndroidApk } from "./downloads";
import { HttpError, json } from "./http";
import { assignMedia, beginUpload, cancelUpload, completeUpload, configureUpload, deleteMedia, importMediaToStream, listMedia, serveMedia, serveStreamSource, streamPlayback, uploadPart, uploadStatus } from "./media";
import { createShow, listShows } from "./shows";
import { addManualSongMatch, deleteSongMatch, failRecognitionAttempt, listSongMatches, prepareRecognitionUpload, recognitionStatus, requestRecognition, reviewSongMatch, serveRecognitionSource, submitRecognition } from "./recognition";
import { createShowShare, createVideoShare, getPublicShow, revokeShowShare, revokeVideoShare, servePublicShowMedia, servePublicVideo, servePublicVideoPreview, showShareStatus, videoShareStatus } from "./sharing";
import { getStorageQuota } from "./storage";

export async function handle(request: Request, env: Env): Promise<Response> {
  const url = new URL(request.url);
  const path = url.pathname;
  const method = request.method.toUpperCase();
  if (path === "/api/health" && method === "GET") return json({ ok: true });
  if (path === "/downloads/concert-thing.apk" && (method === "GET" || method === "HEAD")) return downloadAndroidApk(request, env);
  const recognitionSource = /^\/api\/recognition-source\/([a-f0-9]{64})$/.exec(path);
  if (recognitionSource && method === "GET") return serveRecognitionSource(request, env, recognitionSource[1]);
  const streamSource = /^\/api\/stream-source\/([a-f0-9]{64})$/.exec(path);
  if (streamSource && (method === "GET" || method === "HEAD")) return serveStreamSource(request, env, streamSource[1]);
  const publicShow = /^\/api\/public\/shows\/((?:[A-Za-z0-9]{6}|[a-f0-9]{64}))$/.exec(path);
  if (publicShow && method === "GET") return getPublicShow(request, env, publicShow[1]);
  const publicMedia = /^\/api\/public\/shows\/((?:[A-Za-z0-9]{6}|[a-f0-9]{64}))\/media\/([^/]+)\/content$/.exec(path);
  if (publicMedia && (method === "GET" || method === "HEAD")) return servePublicShowMedia(request, env, publicMedia[1], publicMedia[2]);
  const publicVideoPreview = /^\/video\/((?:[A-Za-z0-9]{6}|[a-f0-9]{64}))\/?$/.exec(path);
  if (publicVideoPreview && (method === "GET" || method === "HEAD")) return servePublicVideoPreview(request, env, publicVideoPreview[1]);
  const publicVideo = /^\/video\/((?:[A-Za-z0-9]{6}|[a-f0-9]{64}))\.mp4$/.exec(path);
  if (publicVideo && (method === "GET" || method === "HEAD")) return servePublicVideo(request, env, publicVideo[1]);
  const auth = await authenticate(request, env);
  if (path === "/api/account/claim-legacy" && method === "POST") return claimLegacyData(env, auth);
  if (path === "/api/admin/status" && method === "GET") return adminStatus(env, auth);
  if (path === "/api/admin/users" && method === "GET") return listAdminUsers(env, auth);
  if (path === "/api/admin/promotions" && method === "POST") return createPromotion(request, env, auth);
  if (path === "/api/account/storage" && method === "GET") {
    return json(await getStorageQuota(env.DB, auth.userId));
  }
  if (path === "/api/shows" && method === "GET") return listShows(env, auth);
  if (path === "/api/shows" && method === "POST") return createShow(request, env, auth);
  let match = /^\/api\/shows\/([^/]+)\/share$/.exec(path);
  if (match && method === "GET") return showShareStatus(request, env, match[1], auth);
  if (match && method === "POST") return createShowShare(request, env, match[1], auth);
  if (match && method === "DELETE") return revokeShowShare(request, env, match[1], auth);
  match = /^\/api\/media\/([^/]+)\/share$/.exec(path);
  if (match && method === "GET") return videoShareStatus(request, env, match[1], auth);
  if (match && method === "POST") return createVideoShare(request, env, match[1], auth);
  if (match && method === "DELETE") return revokeVideoShare(request, env, match[1], auth);
  if (path === "/api/media" && method === "GET") return listMedia(request, env, auth);
  if (path === "/api/song-matches" && method === "GET") return listSongMatches(env, auth);
  if (path === "/api/uploads" && method === "POST") return beginUpload(request, env, auth);
  match = /^\/api\/uploads\/([^/]+)$/.exec(path);
  if (match && method === "GET") return uploadStatus(env, match[1], auth);
  if (match && method === "PATCH") return configureUpload(request, env, match[1], auth);
  if (match && method === "DELETE") return cancelUpload(env, match[1], auth);
  match = /^\/api\/uploads\/([^/]+)\/parts\/(\d+)$/.exec(path);
  if (match && method === "PUT") return uploadPart(request, env, match[1], Number(match[2]), auth);
  match = /^\/api\/uploads\/([^/]+)\/complete$/.exec(path);
  if (match && method === "POST") return completeUpload(request, env, match[1], auth);
  match = /^\/api\/media\/([^/]+)\/assignment$/.exec(path);
  if (match && method === "PATCH") return assignMedia(request, env, match[1], auth);
  match = /^\/api\/media\/([^/]+)$/.exec(path);
  if (match && method === "DELETE") return deleteMedia(env, match[1], auth);
  match = /^\/api\/media\/([^/]+)\/stream$/.exec(path);
  if (match && method === "POST") return importMediaToStream(request, env, match[1], auth);
  if (match && method === "GET") return streamPlayback(env, match[1], auth);
  match = /^\/api\/media\/([^/]+)\/recognition$/.exec(path);
  if (match && method === "POST") return requestRecognition(request, env, match[1], auth);
  if (match && method === "GET") return recognitionStatus(env, match[1], auth);
  match = /^\/api\/media\/([^/]+)\/song-matches$/.exec(path);
  if (match && method === "POST") return addManualSongMatch(request, env, match[1], auth);
  match = /^\/api\/recognition\/([^/]+)\/upload$/.exec(path);
  if (match && method === "POST") return prepareRecognitionUpload(env, match[1], auth);
  match = /^\/api\/recognition\/([^/]+)\/submit$/.exec(path);
  if (match && method === "POST") return submitRecognition(request, env, match[1], auth);
  match = /^\/api\/recognition\/([^/]+)\/fail$/.exec(path);
  if (match && method === "POST") return failRecognitionAttempt(env, match[1], auth);
  match = /^\/api\/song-matches\/([^/]+)$/.exec(path);
  if (match && method === "DELETE") return deleteSongMatch(env, match[1], auth);
  if (match && method === "PATCH") return reviewSongMatch(request, env, match[1], auth);
  match = /^\/api\/media\/([^/]+)\/content$/.exec(path);
  if (match && (method === "GET" || method === "HEAD")) return serveMedia(request, env, match[1], { ownerId: auth.userId });
  throw new HttpError(404, "Not found");
}
